export const points = [
  {
    id: "Alfa",
    name: "UCT1",
    aliases: ["UCT1", "uct1", "Alfa", "alfa"],
    node: 'n36',
    left: 576,
    top: 795,
    height: 20,
    width: 59,
    rotate: -1.8,
  },
  {
    id: "Beta",
    name: "UCT2",
    aliases: ["UCT2", "uct2", "Beta", "beta"],
    node: 'n37',
    left: 577,
    top: 829,
    height: 20,
    width: 57,
    rotate: -1.8,
  },
  {
    id: "Biblioteca",
    name: "Biblioteca",
    aliases: ["Biblioteca", "biblioteca", "becas", "internacionalizacion"],
    node: 'n171',
    left: 540,
    top: 1035,
    height: 73,
    width: 80,
    rotate: 5,
  },
  {
    id: "Entrada Boulevard",
    name: "Entrada Boulevard",
    aliases: ["Entrada", "Boulevard", "Entrada Boulevard", "Entrada maestros", "Blvd"],
    node: 'n90',
    left: 402,
    top: 1087,
    height: 33,
    width: 17,
    rotate: -34,
  },
  {
    id: "CTA",
    name: "CTA",
    aliases: ["Coordinacion de tecnologías", "coordinacion tecnologías", "tecnologías, CTA"],
    node: 'n35',
    left: 640,
    top: 768.5,
    height: 51,
    width: 25,
    rotate: -1.8,
  },
  {
    id: "JOBS",
    name: "JOBS",
    aliases: ["JOBS", "jobs", "salon jobs", "ingles"],
    node: 'n174',
    left: 671,
    top: 652,
    height: 14,
    width: 43,
    rotate: -1,
  },
  {
    id: "JOBS 2",
    name: "JOBS 2",
    aliases: ["JOBS", "jobs", "salon jobs", "ingles"],
    node: 'n173',
    left: 671,
    top: 627,
    height: 14,
    width: 43,
    rotate: -1,
  },
  {
    id: "Titanic",
    name: "Laboratorio de Ingenierías",
    aliases: ["Laboratorio de Ingenierías", "lab ingenierias", "laboratorio de ingenierias", "Lab ing"],
    node: 'n175',
    left: 644,
    top: 528,
    height: 41,
    width: 67,
    rotate: 0,
  },
  {
    id: "Modulo A",
    name: "Módulo A",
    aliases: ["Modulo A", "modulo a", "MA", "edificio a", "M A"],
    node: 'n99',
    left: 493,
    top: 1130,
    height: 140,
    width: 60,
    rotate: -33,
  },
  {
    id: "Modulo B",
    name: "Módulo B",
    aliases: ["Modulo B", "modulo b", "MB", "edificio b", "M B"],
    node: 'n109',
    left: 615,
    top: 1198,
    height: 20,
    width: 55,
    rotate: 7.5,
  },
  {
    id: "Modulo C",
    name: "Módulo C",
    aliases: ["Modulo C", "modulo c", "MC", "edificio c", "M C"],
    node: 'n176',
    left: 603,
    top: 1168,
    height: 20,
    width: 55,
    rotate: 7.5,
  },
  {
    id: "Modulo D",
    name: "Módulo D",
    aliases: ["Modulo D", "modulo d", "MD", "edificio d", "M D"],
    node: 'n104',
    left: 560,
    top: 1119,
    height: 20,
    width: 68,
    rotate: 5,
  },
  {
    id: "Modulo E",
    name: "Módulo E",
    aliases: ["Modulo E", "ME", "Edificio E", "edificio e", "M E"],
    node: 'n132',
    left: 326,
    top: 939,
    height: 25,
    width: 260,
    rotate: -1,
  },
  {
    id: "Modulo F",
    name: "Módulo F",
    aliases: ["Modulo F", "MF", "Edificio F", "edificio f", "M F"],
    node: 'n177',
    left: 479,
    top: 878,
    height: 59,
    width: 44,
    rotate: 0,
  },
  {
    id: "Modulo G",
    name: "Módulo G",
    aliases: ["Modulo G", "MG", "Edificio G", "edificio g", "M G"],
    node: 'n136',
    left: 313,
    top: 883,
    height: 36,
    width: 83,
    rotate: -1,
  },
  {
    id: "Modulo H",
    name: "Módulo H",
    aliases: ["Modulo H", "MH", "Edificio H", "edificio h", "M H"],
    node: 'n184',
    left: 415,
    top: 858,
    height: 19,
    width: 78.8,
    rotate: 1,
  },
  {
    id: "Modulo I",
    name: "Módulo I",
    aliases: ["Modulo I", "MI", "Edificio I", "edificio i", "M I"],
    node: 'n185',
    left: 520,
    top: 858,
    height: 19,
    width: 65,
    rotate: 0,
  },
  {
    id: "Modulo J",
    name: "Módulo J",
    aliases: ["Modulo J", "MJ", "Edificio J", "edificio j", "M J"],
    node: 'n186',
    left: 460,
    top: 832,
    height: 13,
    width: 75,
    rotate: 0,
  },
  {
    id: "Modulo K",
    name: "Módulo K",
    aliases: ["Modulo K", "MK", "Edificio K", "edificio k", "M K"],
    node: 'n30',
    left: 449,
    top: 809,
    height: 12,
    width: 80,
    rotate: -1,
  },
  {
    id: "Modulo L",
    name: "Módulo L",
    aliases: ["Modulo L", "ML", "Edificio L", "edificio l", "M L"],
    node: 'n188',
    left: 570,
    top: 715,
    height: 42,
    width: 75,
    rotate: 0,
  },
  {
    id: "Modulo L2",
    name: "Módulo L2",
    aliases: ["Modulo L2", "ML2", "Edificio L2", "edificio l2", "M L2"],
    node: 'n192',
    left: 533,
    top: 707,
    height: 30,
    width: 20,
    rotate: -2,
  },
  {
    id: "Modulo M",
    name: "Módulo M",
    aliases: ["Modulo M", "MM", "Edificio M", "edificio m", "M M"],
    node: 'n196',
    left: 431,
    top: 752,
    height: 33,
    width: 68,
    rotate: 0.5,
  },
  {
    id: "Modulo N",
    name: "Módulo N",
    aliases: ["Modulo N", "MN", "Edificio N", "edificio n", "M N"],
    node: 'n195',
    left: 430,
    top: 710,
    height: 29,
    width: 70,
    rotate: 0,
  },
  {
    id: "Santander",
    name: "Santander",
    aliases: ["Santander", "Banco Santander", "Cajero"],
    node: 'n195',
    left: 455,
    top: 724,
    height: 15,
    width: 35,
    rotate: 0,
  },
  {
    id: "Modulo O",
    name: "Módulo O",
    aliases: ["Modulo O", "MO", "Edificio O", "edificio o", "M O"],
    node: 'n198',
    left: 425,
    top: 637,
    height: 60,
    width: 65,
    rotate: 1,
  },
  {
    id: "Modulo P",
    name: "Módulo P",
    aliases: ["Edificio P", "MP", "Edificio P", "edificio p", "M P"],
    node: 'n189',
    left: 520,
    top: 645,
    height: 18,
    width: 80,
    rotate: -4,
  },
  {
    id: "Modulo Q",
    name: "Módulo Q",
    aliases: ["Edificio Q", "MQ", "Edificio Q", "edificio q", "M Q"],
    node: 'n44',
    left: 581,
    top: 598,
    height: 18,
    width: 136,
    rotate: -1,
  },
  {
    id: "Modulo Q2",
    name: "Módulo Q2",
    aliases: ["modulo q2", "MQ2", "Edificio Q2", "edificio q2", "M Q2"],
    node: 'n183',
    left: 685,
    top: 698,
    width: 34,
    height: 22,
    rotate: -3,
  },
  {
    id: "Modulo R",
    name: "Módulo R",
    aliases: ["Edificio R", "MR", "Edificio R", "edificio r", "M R"],
    node: 'n142',
    left: 517,
    top: 585,
    height: 24,
    width: 53,
    rotate: -2,
  },
  {
    id: "Modulo S",
    name: "Módulo S",
    aliases: ["Modulo S", "MS", "Edificio S", "edificio s", "M S"],
    node: 'n182',
    left: 423,
    top: 598,
    height: 20,
    width: 70,
    rotate: 0,
  },
  {
    id: "Modulo S2",
    name: "Módulo S2",
    aliases: ["Edificio S2", "MS2", "Edificio S2", "edificio s2", "M S2"],
    node: 'n180',
    left: 410,
    top: 549,
    height: 22,
    width: 28,
    rotate: -0.5,
  },
  {
    id: "Modulo T",
    name: "Módulo T",
    aliases: ["Edificio T", "MT", "Edificio T", "edificio t", "M T"],
    node: 'n46',
    left: 522,
    top: 550,
    height: 18,
    width: 90,
    rotate: 0,
  },
  {
    id: "Modulo U",
    name: "Módulo U",
    aliases: ["Edificio U", "MU", "Edificio U", "edificio u", "M E"],
    node: 'n47',
    left: 523,
    top: 516,
    height: 19,
    width: 91,
    rotate: 0,
  },
  {
    id: "Modulo V",
    name: "Módulo V",
    aliases: ["Edificio V", "MV", "Edificio V", "edificio v", "M V"],
    node: 'n178',
    left: 413,
    top: 479,
    height: 19,
    width: 90,
    rotate: 0,
  },
  {
    id: "Modulo V2",
    name: "Módulo V2",
    aliases: ["Edificio V2", "MV2", "Edificio V2", "edificio v2", "M V2"],
    node: 'n147',
    left: 413,
    top: 515,
    height: 19,
    width: 90,
    rotate: 0,
  },
  {
    id: "Modulo W",
    name: "Módulo Doble V",
    aliases: ["Módulo Doble V", "MW", "Edificio W", "edificio w", "M W"],
    node: 'n200',
    left: 317,
    top: 530,
    height: 17,
    width: 80,
    rotate: 0,
  },
  {
    id: "Modulo X",
    name: "Módulo X",
    aliases: ["modulo x", "MX", "Edificio X", "edificio x", "M X"],
    node: 'n199',
    left: 317,
    top: 496,
    width: 80,
    height: 17,
    rotate: 0,
  },
  {
    id: "Modulo Y",
    name: "Módulo Y",
    aliases: ["Modulo Y", "MY", "Edificio Y", "edificio y", "M Y"],
    node: 'n153',
    left: 280,
    top: 646,
    height: 45,
    width: 68,
    rotate: -4,
  },
  {
    id: "Modulo Z",
    name: "Módulo Z",
    aliases: ["modulo z", "MZ", "Edificio Z", "edificio z", "M Z"],
    node: 'n170',
    left: 253,
    top: 653,
    height: 47,
    width: 17,
    rotate: 5,
  },
  {
    id: "Modulo Z1",
    name: "Módulo Z1",
    aliases: ["modulo z1", "MZ1", "Edificio Z1", "edificio z1", "M Z1"],
    node: 'n169',
    left: 225,
    top: 642,
    height: 53,
    width: 22,
    rotate: 5,
  },
  {
    id: "Modulo Z2",
    name: "Módulo Z2",
    aliases: ["Modulo Z2", "MZ2", "Edificio Z2", "edificio z2", "M Z2"],
    node: 'n155',
    left: 255,
    top: 600,
    height: 19,
    width: 65,
    rotate: -26,
  },
  {
    id: "Entrada Olimpica",
    name: "Entrada Olímpica",
    aliases: ["Entrada", "Olimpica", "Entrada Olimpica", "Entrada alumnos"],
    node: 'n111',
    left: 648,
    top: 1225,
    height: 15,
    width: 23,
    rotate: -22,
  },
  {
    id: "Entrada Revolucion",
    name: "Entrada Revolución",
    aliases: ["Revolucion", "Entrada", "Entrada Revolucion"],
    node: 'n1',
    left: 700,
    top: 275,
    height: 35,
    width: 60,
    rotate: 34,
  },
  {
    id: "comida",
    name: "Comida",
    aliases: ["comida V", "comida X"],
    node: 'n201',
    left: 405,
    top: 318,
    height: 142,
    width: 15,
    rotate: 34,
  },
  {
    id: "Comida15",
    name: "Comida15",
    aliases: ["comida T",],
    node: 'n202',
    left: 632,
    top: 540,
    height: 15,
    width: 15,
    rotate: 34,
  },
  {
    id: "La Flor de Córdoba",
    name: "La Flor de Córdoba",
    aliases: ["comida T", "Café", "Entrada Revolucion"],
    node: 'n203',
    left: 633,
    top: 559,
    height: 15,
    width: 15,
    rotate: 34,
  },
  {
    id: "Cafebreria",
    name: "Cafebrería",
    aliases: ["Cafeteria", "Libreria", "cafebreria", "cafeteria"],
    node: 'n207',
    left: 586,
    top: 763,
    height: 26,
    width: 15,
    rotate: -0.5,
  },
  {
    id: "Comedor de maestros",
    name: "Comedor de Maestros",
    aliases: ["comedor", "Comedor", "Maestros", "Com"],
    node: 'n209',
    left: 479,
    top: 552,
    height: 20,
    width: 28,
    rotate: -0.5,
  },
  {
    id: "Baños S2",
    name: "Baños S2",
    aliases: ["baños S2", "baños s2", "Baños s2", "baños"],
    node: 'n205',
    left: 449,
    top: 552,
    height: 20,
    width: 28,
    rotate: -0.5,
  },
  // Auditorios 
  {
    id: "Auditorio Matute Remus",
    name: "Auditorio Matute Remus",
    aliases: ["Audirorio", "Matute remus", "Matute"],
    node: 'n191',
    left: 529,
    top: 737,
    height: 13,
    width: 28,
  },
  {
    id: "Auditorio Enrique Díaz de León",
    name: "Auditorio Enrique Díaz de León",
    aliases: ["Auditorio", "Enrique Díaz de León", "Modulo A", "MA", "Auditorio MA", "Auditorio Modulo A", "M A"],
    node: 'n99',
    left: 496,
    top: 1144,
    height: 0,
    width: 0,
    rotate: 0,
  },
  {
    id: " Auditorio Antonio Rodríguez Sánchez",
    name: "Auditorio Antonio Rodríguez Sánchez",
    aliases: ["Auditorio", "Antonio Rodríguez Sánchez", "Modulo E", "ME", "Auditorio Modulo E", "Auditorio ME", "M E", "edificio e"],
    node: 'n134',
    left: 484,
    top: 663,
    height: 0,
    width: 0,
    rotate: 0,
  },
  {
    id: "Auditorio Antonio Alatorre",
    name: "Auditorio Antonio Alatorre",
    aliases: ["Auditorio", "Antonio Alatorre", "Modulo O", "MO", "Auditorio Modulo O", "Auditorio MO", "M O", "edificio o"],
    node: 'n198',
    left: 352,
    top: 940,
    height: 0,
    width: 0,
    rotate: 0,
  },
  {
    id: "Auditorio Nikola Mitshievich",
    name: "Auditorio Nikola Mitshievich",
    aliases: ["Auditorio", "Nikola Mitshievich", "Modulo Y", "MY", "Auditorio Modulo Y", "Auditorio MY", "M Y", "edificio y"],
    node: 'n153',
    left: 325,
    top: 638,
    height: 0,
    width: 0,
    rotate: 0,
  },
  {
    id: "Auditorio Modulo Z",
    name: "Auditorio Módulo Z",
    aliases: ["Auditorio", "Módulo Z", "Modulo Z", "MZ", "Auditorio Modulo Z", "Auditorio MZ", "M Z", "edificio z"],
    node: 'n170',
    left: 275,
    top: 673,
    height: 0,
    width: 0,
    rotate: 0,
  }
]