export const points = [
  {
    id: "Alfa",
    name: "UCT1",
    aliases: ["UCT1", "uct1", "Alfa", "alfa"],
    left: 576,
    top: 795,
    height: 20,
    width: 59,
    rotate: -1.8,
  },
  {
    id: "Beta",
    name: "UCT2",
    aliases: ["UCT2", "uct2", "Beta", "beta"],
    left: 577,
    top: 829,
    height: 20,
    width: 57,
    rotate: -1.8,
  },
  {
    id: "Biblioteca",
    name: "Biblioteca",
    aliases: ["Biblioteca", "biblioteca", "becas", "internacionalizacion"],
    left: 536,
    top: 1035,
    height: 70,
    width: 100,
    rotate: 5,
  },
  {
    id: "Entrada Boulevard",
    name: "Entrada Boulevard",
    aliases: ["Entrada", "Boulevard", "Entrada Boulevard", "Entrada maestros", "Blvd"],
    left: 402,
    top: 1087,
    height: 33,
    width: 17,
    rotate: -34,
  },
  {
    id: "CTA",
    name: "CTA",
    aliases: ["Coordinacion de tecnologias", "coordinacion tecnologias", "tecnologias, CTA"],
    left: 640,
    top: 768.5,
    height: 51,
    width: 25,
    rotate: -1.8,
  },
  {
    id: "Globo",
    name: "El Globo",
    aliases: ["Globo", "globo", "restaurante", "comida"],
    left: 606.5,
    top: 860,
    height: 28,
    width: 30,
    rotate: -1.8,
  },
  {
    id: "JOBS",
    name: "JOBS",
    aliases: ["JOBS", "jobs", "salon jobs", "ingles"],
    left: 671,
    top: 652,
    height: 14,
    width: 43,
    rotate: -1,
  },
  {
    id: "JOBS 2",
    name: "JOBS 2",
    aliases: ["JOBS", "jobs", "salon jobs", "ingles"],
    left: 671,
    top: 627,
    height: 14,
    width: 43,
    rotate: -1,
  },
  {
    id: "Titanic",
    name: "Laboratorio de Ingenierias",
    aliases: ["Laboratorio de Ingenierias", "lab ingenierias", "laboratorio de ingenierias", "Lab ing"],
    left: 644,
    top: 528,
    height: 41,
    width: 67,
    rotate: 0,
  },
  {
    id: "Modulo A",
    name: "Modulo A",
    aliases: ["Modulo A", "modulo a", "MA", "edificio a"],
    left: 493,
    top: 1130,
    height: 140,
    width: 60,
    rotate: -33,
  },
  {
    id: "Modulo B",
    name: "Modulo B",
    aliases: ["Modulo B", "modulo b", "MB", "edificio b"],
    left: 615,
    top: 1198,
    height: 20,
    width: 55,
    rotate: 7.5,
  },
  {
    id: "Modulo C",
    name: "Modulo C",
    aliases: ["Modulo C", "modulo c", "MC", "edificio c"],
    left: 603,
    top: 1168,
    height: 20,
    width: 55,
    rotate: 7.5,
  },
  {
    id: "Modulo D",
    name: "Modulo D",
    aliases: ["Modulo D", "modulo d", "MD", "edificio d"],
    left: 560,
    top: 1119,
    height: 20,
    width: 68,
    rotate: 5,
  },
  {
    id: "Modulo E",
    name: "Modulo E",
    aliases: ["Modulo E", "ME", "Edificio E", "edificio e"],
    left: 326,
    top: 939,
    height:25,
    width: 260,
    rotate: -1,
  },

  {
    id: "Modulo F",
    name: "Modulo F",
    aliases: ["Modulo F", "MF", "Edificio F", "edificio f"],
    left: 479,
    top: 878,
    height: 59,
    width: 44,
    rotate: 0,
  },

  {
    id: "Modulo G",
    name: "Modulo G",
    aliases: ["Modulo G", "MG", "Edificio G", "edificio g"],
    left: 313,
    top: 883,
    height: 36,
    width: 83,
    rotate: -1,
  },
  {
    id: "Modulo H",
    name: "Modulo H",
    aliases: ["Modulo H", "MH", "Edificio H", "edificio h"],
    left: 415,
    top: 858,
    height: 19,
    width: 78.8,
    rotate: 1,
  },
  {
    id: "Modulo I",
    name: "Modulo I",
    aliases: ["Modulo I", "MI", "Edificio I", "edificio i"],
    left: 520,
    top: 858,
    height: 19,
    width: 65,
    rotate: 0,
  },
  {
    id: "Modulo J",
    name: "Modulo J",
    aliases: ["Modulo J", "MJ", "Edificio J", "edificio j"],
    left: 460,
    top: 832,
    height: 13,
    width: 75,
    rotate: 0,
  },
  {
    id: "Modulo K",
    name: "Modulo K",
    aliases: ["Modulo K", "MK", "Edificio K", "edificio k"],
    left: 449,
    top: 809,
    height: 12,
    width: 80,
    rotate: -1,
  },
  {
    id: "Modulo L",
    name: "Modulo L",
    aliases: ["Modulo L", "ML", "Edificio L", "edificio l"],
    left: 570,
    top: 715,
    height: 42,
    width: 75,
    rotate: 0,
  },
  {
    id: "Modulo L2",
    name: "Modulo L2",
    aliases: ["Modulo L2", "ML2", "Edificio L2", "edificio l2"],
    left: 533,
    top: 707,
    height: 30,
    width: 20,
    rotate: -2,
  },
  {
    id: "Modulo M",
    name: "Modulo M",
    aliases: ["Modulo M", "MM", "Edificio M", "edificio m"],
    left: 431,
    top: 752,
    height: 33,
    width: 68,
    rotate: 0.5,
  },
  {
    id: "Modulo N",
    name: "Modulo N",
    aliases: ["Modulo N", "MN", "Edificio N", "edificio n"],
    left: 430,
    top: 710,
    height: 29,
    width: 70,
    rotate: 0,
  },
  {
    id: "Modulo O",
    name: "Modulo O",
    aliases: ["Modulo O", "MO", "Edificio O", "edificio o"],
    left: 425,
    top: 637,
    height: 60,
    width: 65,
    rotate: 1,
  },
  {
    id: "Modulo P",
    name: "Modulo P",
    aliases: ["Edificio P", "MP", "Edificio P", "edificio p"],
    left: 520,
    top: 645,
    height: 18,
    width: 80,
    rotate:-4,
  },
  {
    id: "Modulo Q",
    name: "Modulo Q",
    aliases: ["Edificio Q", "MQ", "Edificio Q", "edificio q"],
    left: 581,
    top: 598,
    height: 18,
    width: 136,
    rotate: -1,
  },
  {
    id: "Modulo Q2",
    name: "Modulo Q2",
    aliase: ["modulo q2", "Edificio Q2", "edificio q2"],
    left: 685,
    top: 698,
    width: 34,
    height: 22,
    rotate:-3,
  },
  {
    id: "Modulo R",
    name: "Modulo R",
    aliases: ["Edificio R", "MR", "Edificio R", "edificio r"],
    left: 517,
    top: 585,
    height: 24,
    width: 53,
    rotate: -2,
  },
  {
    id: "Modulo S",
    name: "Modulo S",
    aliases: ["Modulo S", "MS", "Edificio S", "edificio s"],
    left: 423,
    top: 598,
    height: 20,
    width: 70,
    rotate: 0,
  },
  {
    id: "Modulo S2",
    name: "Modulo S2",
    aliases: ["Edificio S2", "MS2", "Edificio S2", "edificio s2"],
    left: 410,
    top: 549,
    height: 22,
    width: 28,
    rotate: -0.5,
  },
  {
    id: "Modulo T",
    name: "Modulo T",
    aliases: ["Edificio T", "MT", "Edificio T", "edificio t"],
    left: 522,
    top: 550,
    height: 18,
    width: 90,
    rotate: 0,
  },
  {
    id: "Modulo U",
    name: "Modulo U",
    aliases: ["Edificio U", "MU", "Edificio U", "edificio u"],
    left: 523,
    top: 516,
    height: 19,
    width: 91,
    rotate: 0,
  },
  {
    id: "Modulo V",
    name: "Modulo V",
    aliases: ["Edificio V", "MV", "Edificio V", "edificio v"],
    left: 413,
    top: 479,
    height: 19,
    width: 90,
    rotate: 0,
  },
  {
    id: "Modulo V2",
    name: "Modulo V2",
    aliases: ["Edificio V2", "MV2", "Edificio V2", "edificio v2"],
    left: 413,
    top: 515,
    height: 19,
    width: 90,
    rotate: 0,
  },
  {
    id: "Modulo W",
    name: "Modulo W",
    aliases: ["Módulo Doble V", "MW","Edificio W", "edificio w"],
    left: 317,
    top: 530,
    height: 17,
    width: 80,
    rotate: 0,
  },
  {
    id: "Modulo X",
    name: "Modulo X",
    aliase: ["modulo x", "Edificio X", "edificio x"],
    left: 317,
    top: 496,
    width: 80,
    height: 17,
    rotate:0,
  },
  {
    id: "Modulo Y",
    name: "Modulo Y",
    aliases: ["Modulo Y", "MY", "Edificio Y", "edificio y"],
    left: 280,
    top: 646,
    height: 45,
    width: 68,
    rotate: -4,
  },
  {
    id: "Modulo Z",
    name: "Modulo Z",
    aliases: ["modulo z", "Edificio Z", "edificio z"],
    left: 253,
    top: 653,
    height: 47,
    width: 17,
    rotate: 5,
  },
  {
    id: "Modulo Z1",
    name: "Modulo Z1",
    aliases: ["modulo z1", "Edificio Z1", "edificio z1"],
    left: 225,
    top: 642,
    height: 53,
    width: 22,
    rotate: 5,
  },
  {
    id: "Modulo Z2",
    name: "Modulo Z2",
    aliases: ["Modulo Z2", "MZ2", "Edificio Z2", "edificio z2"],
    left: 255,
    top: 600,
    height: 19,
    width: 65,
    rotate: -26,
  },
  {
    id: "Entrada Olimpica",
    name: "Entrada Olimpica",
    aliases: ["Entrada", "Olimpica", "Entrada Olimpica", "Entrada alumnos"],
    left: 648,
    top: 1225,
    height: 15,
    width: 23,
    rotate: -22,
  },
  // {
  //   id: "Pista",
  //   name: "Pista de Atletismo",
  //   aliases: ["Atletismo", "atletismo", "pista de atletismo", "Pista de atletismo","runneros", ],
  //   left: 730,
  //   top: 922,
  //   height: 150,
  //   width: 100,
  //   rotate: -4,
  // },
  {
    id: "Entrada Revolucion",
    name: "Entrada Revolucion",
    aliases: ["Revolucion", "Entrada", "Entrada Revolucion"],
    left: 700,
    top: 275,
    height: 35,
    width: 60,
    rotate: 34,
  },
  {
    id: "comida1",
    name: "comida1",
    aliases: ["Revolucion", "Entrada", "Entrada Revolucion"],
    left: 410,
    top: 444,
    height: 15,
    width: 15,
    rotate: 34,
  },
  {
    id: "comida2",
    name: "comida2",
    aliases: ["Revolucion", "Entrada", "Entrada Revolucion"],
    left: 410,
    top: 425,
    height: 15,
    width: 15,
    rotate: 34,
  },
  {
    id: "comida3",
    name: "comida3",
    aliases: ["Revolucion", "Entrada", "Entrada Revolucion"],
    left: 409,
    top: 405,
    height: 15,
    width: 15,
    rotate: 34,
  },
  {
    id: "comida4",
    name: "comida4",
    aliases: ["Revolucion", "Entrada", "Entrada Revolucion"],
    left: 408,
    top: 388,
    height: 15,
    width: 15,
    rotate: 34,
  },
  {
    id: "comida5",
    name: "comida5",
    aliases: ["Revolucion", "Entrada", "Entrada Revolucion"],
    left: 408,
    top: 369,
    height: 15,
    width: 15,
    rotate: 34,
  },
  {
    id: "comida6",
    name: "comida6",
    aliases: ["Revolucion", "Entrada", "Entrada Revolucion"],
    left: 408,
    top: 352,
    height: 15,
    width: 15,
    rotate: 34,
  },
  {
    id: "comida7",
    name: "comida7",
    aliases: ["Revolucion", "Entrada", "Entrada Revolucion"],
    left: 408,
    top: 333,
    height: 15,
    width: 15,
    rotate: 34,
  },
  {
    id: "comida8",
    name: "comida8",
    aliases: ["Revolucion", "Entrada", "Entrada Revolucion"],
    left: 408,
    top: 315,
    height: 15,
    width: 15,
    rotate: 34,
  },
  {
    id: "comida9",
    name: "comida9",
    aliases: ["comida P", "Entrada", "Entrada Revolucion"],
    left: 601,
    top: 645,
    height: 15,
    width: 15,
    rotate: 34,
  },
  {
    id: "comida10",
    name: "comida10",
    aliases: ["comida P", "Entrada", "Entrada Revolucion"],
    left: 616,
    top: 645,
    height: 15,
    width: 15,
    rotate: 34,
  },
  {
    id: "comida11",
    name: "comida11",
    aliases: ["comida P", "Entrada", "Entrada Revolucion"],
    left: 630,
    top: 645,
    height: 15,
    width: 15,
    rotate: 34,
  },
  {
    id: "comida12",
    name: "comida12",
    aliases: ["comida P", "Entrada", "Entrada Revolucion"],
    left: 643,
    top: 645,
    height: 15,
    width: 15,
    rotate: 34,
  },
  {
    id: "comida13",
    name: "comida13",
    aliases: ["comida T", "Entrada", "Entrada Revolucion"],
    left: 610,
    top: 563,
    height: 15,
    width: 15,
    rotate: 34,
  },
  {
    id: "comida14",
    name: "comida14",
    aliases: ["comida T", "Entrada", "Entrada Revolucion"],
    left: 610,
    top: 545,
    height: 15,
    width: 15,
    rotate: 34,
  },
  {
    id: "comida15",
    name: "comida15",
    aliases: ["comida T", "Entrada", "Entrada Revolucion"],
    left: 632,
    top: 540,
    height: 15,
    width: 15,
    rotate: 34,
  },
  {
    id: "La Flor de Córdoba",
    name: "La Flor de Córdoba",
    aliases: ["comida T", "Café", "Entrada Revolucion"],
    left: 633,
    top: 559,
    height: 15,
    width: 15,
    rotate: 34,
  },
  {
    id: "Construcción",
    name: "Construcción",
    aliases: ["Construcción", "Reparacion", "Remodelación"],
    left: 582,
    top: 573,
    height: 15,
    width: 15,
    rotate: 34,
  },
  {
    id: "Construcción laboratorio de ingenierias",
    name: "Construcción laboratorio de ingenierias",
    aliases: ["Construcción", "Reparacion", "Remodelación"],
    left: 673,
    top: 573,
    height: 15,
    width: 15,
    rotate: 34,
  },
  {
    id: "Construcción K",
    name: "Construcción K",
    aliases: ["Construcción", "Reparacion", "Remodelación"],
    left: 523,
    top: 818,
    height: 15,
    width: 15,
    rotate: 34,
  },
  {
    id: "Construcción Q2",
    name: "Construcción Q2",
    aliases: ["Construcción", "Reparacion", "Remodelación"],
    left: 661,
    top: 725,
    height: 30,
    width: 30,
    rotate: 34,
  },
  {
    id: "Cafebreria",
    name: "Cafebreria",
    aliases: ["Cafeteria", "Libreria", "cafebreria", "cafeteria"],
    left: 586,
    top: 763,
    height: 26,
    width: 15,
    rotate: -0.5,
  },
  {
    id: "Comedor de maestros",
    name: "Comedor de maestros",
    aliases: ["comedor", "Comedor", "Maestros", "Com"],
    left: 479,
    top: 552,
    height: 20,
    width: 28,
    rotate: -0.5,
  },
  {
    id: "Baños S2",
    name: "Baños S2",
    aliases: ["baños S2", "baños s2", "Baños s2", "baños"],
    left: 449,
    top: 552,
    height: 20,
    width: 28,
    rotate: -0.5,
  },
]