export const points = [
  {
    id: "Alfa",
    name: "UCT1",
    aliases: ["UCT1", "uct1", "Alfa", "alfa"],
    left: 581,
    top: 788,
    height: 20,
    width: 59,
    rotate: -1.8,
  },
  {
    id: "Beta",
    name: "UCT2",
    aliases: ["UCT2", "uct2", "Beta", "beta"],
    left: 585,
    top: 820,
    height: 20,
    width: 57,
    rotate: -1.8,
  },
  {
    id: "Biblioteca",
    name: "Biblioteca",
    aliases: ["Biblioteca", "biblioteca", "becas", "internacionalizacion"],
    left: 536,
    top: 1022,
    height: 70,
    width: 100,
    rotate: 5,
  },
  {
    id: "Entrada Boulevard",
    name: "Entrada Boulevard",
    aliases: ["Entrada", "Boulevard", "Entrada Boulevard", "Entrada maestros", "Blvd"],
    left: 410,
    top: 1095,
    height: 38,
    width: 35,
    rotate: -34,
  },
  {
    id: "CTA",
    name: "CTA",
    aliases: ["Coordinacion de tecnologias", "coordinacion tecnologias", "tecnologias, CTA"],
    left: 647.5,
    top: 768.5,
    height: 51,
    width: 30.5,
    rotate: -1.8,
  },
  {
    id: "Globo",
    name: "El Globo",
    aliases: ["Globo", "globo", "restaurante", "comida"],
    left: 606.5,
    top: 860,
    height: 28,
    width: 30,
    rotate: -1.8,
  },
  {
    id: "JOBS",
    name: "JOBS",
    aliases: ["JOBS", "jobs", "salon jobs", "ingles"],
    left: 683,
    top: 652,
    height: 12,
    width: 43,
    rotate: -1,
  },
  {
    id: "JOBS 2",
    name: "JOBS 2",
    aliases: ["JOBS", "jobs", "salon jobs", "ingles"],
    left: 681,
    top: 622,
    height: 11,
    width: 43,
    rotate: -1,
  },
  {
    id: "Titanic",
    name: "Laboratorio de Ingenierias",
    aliases: ["Laboratorio de Ingenierias", "lab ingenierias", "laboratorio de ingenierias", "Lab ing"],
    left: 644,
    top: 526,
    height: 53,
    width: 80,
    rotate: -4,
  },
  {
    id: "Modulo A",
    name: "Modulo A",
    aliases: ["Modulo A", "modulo a", "MA", "edificio a"],
    left: 504,
    top: 1105,
    height: 154,
    width: 65,
    rotate: -34,
  },
  {
    id: "Modulo B",
    name: "Modulo B",
    aliases: ["Modulo B", "modulo b", "MB", "edificio b"],
    left: 625,
    top: 1178,
    height: 20,
    width: 64,
    rotate: 7.5,
  },
  {
    id: "Modulo C",
    name: "Modulo C",
    aliases: ["Modulo C", "modulo c", "MC", "edificio c"],
    left: 605,
    top: 1145,
    height: 20,
    width: 64,
    rotate: 7.5,
  },
  {
    id: "Modulo D",
    name: "Modulo D",
    aliases: ["Modulo D", "modulo d", "MD", "edificio d"],
    left: 560,
    top: 1100,
    height: 20,
    width: 80,
    rotate: 7.5,
  },
  {
    id: "Modulo E",
    name: "Modulo E",
    aliases: ["Modulo E", "ME", "Edificio E", "edificio e"],
    left: 316,
    top: 929,
    height:25,
    width: 311,
    rotate: -4,
  },
  {
    id: "Modulo F",
    name: "Modulo F",
    aliases: ["Modulo F", "MF", "Edificio F", "edificio f"],
    left: 478,
    top: 852,
    height: 75,
    width: 50,
    rotate: -2,
  },
  {
    id: "Modulo G",
    name: "Modulo G",
    aliases: ["Modulo G", "MG", "Edificio G", "edificio g"],
    left: 305,
    top: 869,
    height: 36,
    width: 85,
    rotate: -3,
  },
  {
    id: "Modulo H",
    name: "Modulo H",
    aliases: ["Modulo H", "MH", "Edificio H", "edificio h"],
    left: 398.5,
    top: 855,
    height: 23.5,
    width: 78.8,
    rotate: -3,
  },
  {
    id: "Modulo I",
    name: "Modulo I",
    aliases: ["Modulo I", "MI", "Edificio I", "edificio i"],
    left: 527,
    top: 850,
    height: 16,
    width: 65,
    rotate: -3,
  },
  {
    id: "Modulo J",
    name: "Modulo J",
    aliases: ["Modulo J", "MJ", "Edificio J", "edificio j"],
    left: 459,
    top: 827,
    height: 13,
    width: 78,
    rotate: -3,
  },
  {
    id: "Modulo K",
    name: "Modulo K",
    aliases: ["Modulo K", "MK", "Edificio K", "edificio k"],
    left: 430,
    top: 800,
    height: 18,
    width: 106,
    rotate: -2,
  },
  {
    id: "Modulo L",
    name: "Modulo L",
    aliases: ["Modulo L", "ML", "Edificio L", "edificio l"],
    left: 574,
    top: 708,
    height: 62,
    width: 97,
    rotate: -1.8,
  },
  {
    id: "Modulo L2",
    name: "Modulo L2",
    aliases: ["Modulo L2", "ML2", "Edificio L2", "edificio l2"],
    left: 536.5,
    top: 714,
    height: 42,
    width: 21.5,
    rotate: -2,
  },
  {
    id: "Modulo M",
    name: "Modulo M",
    aliases: ["Modulo M", "MM", "Edificio M", "edificio m"],
    left: 431,
    top: 748,
    height: 35,
    width: 75,
    rotate: 0.5,
  },
  {
    id: "Modulo N",
    name: "Modulo N",
    aliases: ["Modulo N", "MN", "Edificio N", "edificio n"],
    left: 429,
    top: 710,
    height: 20,
    width: 77,
    rotate: -4,
  },
  {
    id: "Modulo O",
    name: "Modulo O",
    aliases: ["Modulo O", "MO", "Edificio O", "edificio o"],
    left: 425,
    top: 637,
    height: 60,
    width: 67,
    rotate: -3,
  },
  {
    id: "Modulo P",
    name: "Modulo P",
    aliases: ["Edificio P", "MP", "Edificio P", "edificio p"],
    left: 527,
    top: 650,
    height: 15,
    width: 137,
    rotate: -2.5,
  },
  {
    id: "Modulo Q",
    name: "Modulo Q",
    aliases: ["Edificio Q", "MQ", "Edificio Q", "edificio q"],
    left: 585,
    top: 603,
    height: 18,
    width: 136,
    rotate: -2,
  },
  {
    id: "Modulo R",
    name: "Modulo R",
    aliases: ["Edificio R", "MR", "Edificio R", "edificio r"],
    left: 523,
    top: 595,
    height: 14,
    width: 53,
    rotate: -2,
  },
  {
    id: "Modulo S",
    name: "Modulo S",
    aliases: ["Modulo S", "MS", "Edificio S", "edificio s"],
    left: 420,
    top: 595,
    height: 26,
    width: 76,
    rotate: -2,
  },
  {
    id: "Modulo S2",
    name: "Modulo S2",
    aliases: ["Edificio S2", "MS2", "Edificio S2", "edificio s2"],
    left: 414,
    top: 554,
    height: 22,
    width: 28,
    rotate: -0.5,
  },
  {
    id: "Modulo T",
    name: "Modulo T",
    aliases: ["Edificio T", "MT", "Edificio T", "edificio t"],
    left: 525,
    top: 556,
    height: 14,
    width: 100,
    rotate: 0,
  },
  {
    id: "Modulo U",
    name: "Modulo U",
    aliases: ["Edificio U", "MU", "Edificio U", "edificio u"],
    left: 527,
    top: 524,
    height: 19,
    width: 95,
    rotate: 0,
  },
  {
    id: "Modulo V",
    name: "Modulo V",
    aliases: ["Edificio V", "MV", "Edificio V", "edificio v"],
    left: 413,
    top: 494,
    height: 19,
    width: 90,
    rotate: -2,
  },
  {
    id: "Modulo V2",
    name: "Modulo V2",
    aliases: ["Edificio V2", "MV2", "Edificio V2", "edificio v2"],
    left: 414,
    top: 524,
    height: 19,
    width: 90,
    rotate: -2,
  },
  {
    id: "Modulo W",
    name: "Modulo W",
    aliases: ["Módulo Doble V", "MW","Edificio W", "edificio w"],
    left: 314,
    top: 535,
    height: 17,
    width: 83,
    rotate: -2,
  },
  {
    id: "Modulo X",
    name: "Modulo X",
    aliase: ["modulo x", "Edificio X", "edificio x"],
    left: 309,
    top: 505,
    width: 84,
    height: 20,
    rotate:-3,
  },
  {
    id: "Modulo Y",
    name: "Modulo Y",
    aliases: ["Modulo Y", "MY", "Edificio Y", "edificio y"],
    left: 270,
    top: 648,
    height: 45,
    width: 72,
    rotate: -5,
  },
  {
    id: "Modulo Z",
    name: "Modulo Z",
    aliases: ["modulo z", "Edificio Z", "edificio z"],
    left: 240,
    top: 653,
    height: 42,
    width: 17,
    rotate: 5,
  },
  {
    id: "Modulo Z1",
    name: "Modulo Z1",
    aliases: ["modulo z1", "Edificio Z1", "edificio z1"],
    left: 213,
    top: 639,
    height: 53,
    width: 22,
    rotate: 5,
  },
  {
    id: "Modulo Z2",
    name: "Modulo Z2",
    aliases: ["Modulo Z2", "MZ2", "Edificio Z2", "edificio z2"],
    left: 243,
    top: 602,
    height: 18,
    width: 67,
    rotate: -24,
  },
  {
    id: "Entrada Olimpica",
    name: "Entrada Olimpica",
    aliases: ["Entrada", "Olimpica", "Entrada Olimpica", "Entrada alumnos"],
    left: 685,
    top: 1195,
    height: 20,
    width: 25,
    rotate: -22,
  },
  // {
  //   id: "Pista",
  //   name: "Pista de Atletismo",
  //   aliases: ["Atletismo", "atletismo", "pista de atletismo", "Pista de atletismo","runneros", ],
  //   left: 730,
  //   top: 922,
  //   height: 150,
  //   width: 100,
  //   rotate: -4,
  // },
  {
    id: "Entrada Revolucion",
    name: "Entrada Revolucion",
    aliases: ["Revolucion", "Entrada", "Entrada Revolucion"],
    left: 700,
    top: 275,
    height: 35,
    width: 60,
    rotate: 34,
  },
]