export const routeVideos = {
  // Videos locales
  "Modulo X - Modulo Z": require("./route_videos/N-UCT1.mp4"),

  // Videos desde Google Drive
  "Modulo X - Modulo V": "https://drive.google.com/uc?id=1-rdjSOCO1WniPoEWqkTkwNKa-FWkRBcr&export=download",
  "Biblioteca - Modulo V": "https://drive.google.com/uc?id=12c0GrLVgw84gjcqA-fYZCpFiynvd24GP&export=download",
  "Modulo O - Modulo G": "https://drive.google.com/uc?id=1AGM5tCLLu83QS4TewcH95UHmIfdLUQrU&export=download",
  "Modulo O - Modulo V2": "https://drive.google.com/uc?id=19wDsW6XCooL4tqUGvHGKHYWnAVY_jji6&export=download",
  "Modulo O - Modulo V": "https://drive.google.com/uc?id=19tjJn_0AmThRQRFXWsO-5IczF7VPuPan&export=download",
  "Modulo O - Entrada Boulevard": "https://drive.google.com/uc?id=19l4aKqqcFzs40EIAbwyUzVx_7BBib-zF&export=download",
  "Modulo N - Modulo V": "https://drive.google.com/uc?id=19idW51Um6DMYA3UW6S4-xR81XjwX0puB&export=download",
  "Modulo N - Modulo A": "https://drive.google.com/uc?id=19eoTDfC2o6_TSI_VWKod-vvLQkgv8uUW&export=download",
  "Modulo N - Entrada Boulevard": "https://drive.google.com/uc?id=19dnQJRF0GHt7YeD-gjb8op4Smd4uQFX5&export=download",
  "Modulo N - Modulo V2": "https://drive.google.com/uc?id=19XSyUXfxS7htbnOT81dZ_gRlBdEdprK1&export=download",
  "Modulo N - Modulo J": "https://drive.google.com/uc?id=19U0bvcf8VpPWkWDWaKMDU8XLGDyAznlV&export=download",
  "Modulo N - Modulo G": "https://drive.google.com/uc?id=19SpGmjBhWsGOgEbvSCrYY1k3T2fZAXpg&export=download",
  "Modulo N - Modulo F": "https://drive.google.com/uc?id=19SCjnTSy-BhDmqeeWtkJOg6CHI2RELid&export=download",
  "Modulo N - Modulo E": "https://drive.google.com/uc?id=19Lv3mxxB5gLygA0IPx_PzXoOFJ9yVhbA&export=download",
  "Modulo N - Biblioteca": "https://drive.google.com/uc?id=192pqWXmOrVs1cDikTVofrAmBq4UaZZ9N&export=download",
  "Modulo O - Modulo K": "https://drive.google.com/uc?id=15Yg2DPSTjOidcZWF65tWxyRg218TdPBB&export=download",
  "Modulo O - Modulo J": "https://drive.google.com/uc?id=15XJ-I2eV8V8CKWWnzPl6g5ZCfkDYa99k&export=download",
  "Modulo O - Modulo F": "https://drive.google.com/uc?id=15XIHov1f2jhNm8f0eDjOtvrkr6ZcDzmO&export=download",
  "Modulo O - Modulo E": "https://drive.google.com/uc?id=15RMVMz1i6aa4Ki7x6E2exi2mEXPLZ4EA&export=download",
  "Modulo V - Entrada Boulevard": "https://drive.google.com/uc?id=15QiELjPJ6xur4HCnyiGXA-kqX8qEsaSf&export=download",
  "Modulo V - Biblioteca": "https://drive.google.com/uc?id=15GB3s6abQR2SkUomN_J5HI2LqgUPSuQg&export=download",
  "Modulo V2 - Entrada Boulevard": "https://drive.google.com/uc?id=14_4SGq46PbwFk_sTX9rTbgPhr8Hf7Iwy&export=download",
  "Modulo V2 - Biblioteca": "https://drive.google.com/uc?id=14W83Za7QIeQ_Bf1ahVXmLQN-7nHz95sw&export=download",
  "Modulo S - Modulo V2": "https://drive.google.com/uc?id=14VbPGoFunZJPcYQXxmABOXlNprWkgCUy&export=download",
  "Modulo S - Modulo V": "https://drive.google.com/uc?id=14S9R1rw19nrZvcxZCbXl-dXqav9eECIS&export=download",
  "Modulo S - Entrada Boulevard": "https://drive.google.com/uc?id=14NPsXe4-go1jhf7ff2IbG_rztMRFvLR4&export=download",
  "Modulo S - Biblioteca": "https://drive.google.com/uc?id=14MpzsS8np6SSv9vDZ1vkvPLM5xmJCVBG&export=download",
  "Modulo O - Modulo A": "https://drive.google.com/uc?id=14DoyR7EG4LdRj5g0PFMFtuNfXl43PZxk&export=download",
  "Modulo V - Modulo O": "https://drive.google.com/uc?id=149RkdEd50zAc70bM46XrczBL0tw_Y-8c&export=download",
  "Modulo V - Modulo N": "https://drive.google.com/uc?id=145v6VIfBIOWjo2APE3IDOuwSIJSa_-RY&export=download",
  "Modulo V - Modulo M": "https://drive.google.com/uc?id=144qHuNaoitiZ6cQUpNjtOoTN2BubD6Wu&export=download",
  "Modulo V - Modulo K": "https://drive.google.com/uc?id=143Ub-AFFjiAkhGB7e0Tf4dlpI_P4i8CS&export=download",
  "Modulo V - Modulo J": "https://drive.google.com/uc?id=13w1nF6NLkSRv59FypPDoxT_TBA277VWr&export=download",
  "Modulo V - Modulo F": "https://drive.google.com/uc?id=13nK6mNd4FHIF6NRSJHEJ9dd01mGk86Qf&export=download",
  "Modulo V - Modulo E": "https://drive.google.com/uc?id=13kv_dgtucWB2DmQkn5Ev-2T20kSrY59T&export=download",
  "Modulo V - Modulo G": "https://drive.google.com/uc?id=13j9n2OlNT0QsxZivIKn_GLWqny6pxPLU&export=download",
  "Modulo V2 - Modulo G": "https://drive.google.com/uc?id=13hf5-nKCEgt3v2Ovb4AO_dw3kO9QZJbl&export=download",
  "Modulo S - Modulo A": "https://drive.google.com/uc?id=13giOWdN-_8bQ4rBHAfWR5EBUVV2d2oBj&export=download",
  "Biblioteca - Entrada Boulevard": "https://drive.google.com/uc?id=12lOqVXx86hb7OBfDJK-3gTgaRKNJGP4t&export=download",
  "Modulo V2 - Modulo V": "https://drive.google.com/uc?id=13amjxBULd5wLyHIlfbsUid7e5MoQH8bM&export=download",
  "Modulo V2 - Modulo S": "https://drive.google.com/uc?id=13XoFITQhyybA0d6nVWxGYS7UMqSFFwsk&export=download",
  "Modulo V2 - Modulo O": "https://drive.google.com/uc?id=13RBFvwlkAH71ehMSPFJFjfSMqHozkpRH&export=download",
  "Modulo V2 - Modulo M": "https://drive.google.com/uc?id=13JNtHwJZRxxL7QfwKjm_ErCD6Eu-m3rA&export=download",
  "Modulo V2 - Modulo N": "https://drive.google.com/uc?id=13DzW-E38RGa2Zf3NKBdRvSmG0uZdlyet&export=download",
  "Modulo V2 - Modulo K": "https://drive.google.com/uc?id=13CWdnZB6UdcQJh7PJnxprzaicpN4Kcou&export=download",
  "Modulo V2 - Modulo J": "https://drive.google.com/uc?id=13C-xKwQS0fpXSdP8_VzhRW59D329Xt5A&export=download",
  "Modulo V2 - Modulo F": "https://drive.google.com/uc?id=137c8pQgdNykEbbwAKkecmYGEksD5KwiO&export=download",
  "Modulo V2 - Modulo E": "https://drive.google.com/uc?id=137SNOgt-H-TzoiDGN6LMlE2ME0lykqWv&export=download",
  "Modulo V2 - Modulo A": "https://drive.google.com/uc?id=12rgie6oto7WXHB3TNjRHIsPWdUTzt85_&export=download",
  "Biblioteca - Modulo V2": "https://drive.google.com/uc?id=12hN87wDHiAOoKvjVK9xxFo0Jd7qQDhhF&export=download",
  "Biblioteca - Modulo V": "https://drive.google.com/uc?id=12c0GrLVgw84gjcqA-fYZCpFiynvd24GP&export=download",
  "Biblioteca - Modulo S": "https://drive.google.com/uc?id=12X74xoor4gHiCj5TmvyQLVOoHPmpwhKb&export=download",
  "Biblioteca - Modulo O": "https://drive.google.com/uc?id=12OeEPs36Cxa5RdjwiuD33C1M5epBWtYw&export=download",
  "Entrada Boulevard - Modulo M": "https://drive.google.com/uc?id=12GYoF9_p6bRrrA5XP_0djUa87gyOPf3t&export=download",
  "Biblioteca - Modulo A": "https://drive.google.com/uc?id=12NVfZww4y_8WM0LxIlzYS3WX-_aC8HCL&export=download",
  "Entrada Boulevard - Modulo N": "https://drive.google.com/uc?id=12I4PIydu_kSUuSRnryLDKe83NV8EDvAI&export=download",
  "Entrada Boulevard - O": "https://drive.google.com/uc?id=12A20jKZePKhYE63g63BranUkz-rf4Hb-&export=download",
  "Entrada Boulevard - Modulo S": "https://drive.google.com/uc?id=128e1SHOjY0Rdfa4sLcx-1V8iyX66gvCd&export=download",
  "Modulo V - Modulo S": "https://drive.google.com/uc?id=1272G27ZK_W-ZBbd3uWaVcD6CwYM4_atV&export=download",
  "Entrada Boulevard - Modulo V2": "https://drive.google.com/uc?id=12-GHcgA1zMfGghSM_z5MHOKZp6XtgW3O&export=download",
  "Entrada Boulevard - Modulo K": "https://drive.google.com/uc?id=11yNHsRJGY2OFyoKpsEKviing2U9XBwqp&export=download",
  "Entrada Boulevard - Modulo V": "https://drive.google.com/uc?id=11vtPj2gMDdhJ8895uiCv_NtyrkRG0xU7&export=download",
  "Entrada Revolución - Modulo N": "https://drive.google.com/uc?id=1oLb1LkZTpng53oheoShqvL9Fs8cdBYun&export=download",
  "Modulo Q - Modulo P": "https://drive.google.com/uc?id=1sMygjAAogC2yE_5yoJF48wZJ3u9xp7Tf&export=download",
  "Modulo Q - Modulo O": "https://drive.google.com/uc?id=1sJLLtyjefORoe67vNbuP3H7N1Tx5Ibhp&export=download",
  "Modulo Q - Modulo N": "https://drive.google.com/uc?id=1s8HHcbUf54D6AlHhg3u30wRsZyIT_m9Z&export=download",
  "Modulo P - Modulo O": "https://drive.google.com/uc?id=1sd_XTeRnFLnP6MzwmQi_-a0pRNLGb3AD&export=download",
  "Modulo P - Modulo N": "https://drive.google.com/uc?id=1sUWCTZ4oPH3jrv243zUn1q0Ks8iEbv_M&export=download",
  "Modulo O - Modulo U": "https://drive.google.com/uc?id=1pordUL6Z0YAsRrR0ajFLuy9EV9zGzT7M&export=download",
  "Modulo O - Modulo T": "https://drive.google.com/uc?id=1q1F14OQZOBrJpaVefY1_n2zrktiRYlRK&export=download",
  "Modulo M - Modulo UTC1": "https://drive.google.com/uc?id=1cGfQceINi5u7QBZYFDG8GwcXDFe3cSxB&export=download",
  "Modulo K - Modulo UTC1": "https://drive.google.com/uc?id=1ccS1nZ8fVCl1a7_BDXbWVbk6WASfBodO&export=download",
  "Modulo K - Modulo S": "https://drive.google.com/uc?id=1tY--NmM6xQVjmWWJXDMO6td1dTtOAlNO&export=download",
  "Modulo K - Modulo O": "https://drive.google.com/uc?id=1tc2-Azz2Ns5iXOBa6bcX4bJx_ieIWnT0&export=download",
  "Modulo K - Modulo N": "https://drive.google.com/uc?id=1d3Ya9OU2_zthatSygfB4_fbgXY7bDV9c&export=download",
  "Modulo K - Modulo M": "https://drive.google.com/uc?id=1d3lS2VgKMnSDx5Lf61pZ1iW5QME9Sz1e&export=download",
  "Entrada Boulevard - Modulo K": "https://drive.google.com/uc?id=11WZEBm_cwywN5TppEkHhMproRHeaTa_J&export=download",
  "Entrada Boulevard - Modulo J": "https://drive.google.com/uc?id=11Rfutngj_CJnyievCkpmswzyiQKhsuw8&export=download",
  "Entrada Boulevard - Modulo F": "https://drive.google.com/uc?id=11MOFscOrIRYMFEsK35nCKfYdq2SmJYuj&export=download",
  "Entrada Boulevard - Modulo E": "https://drive.google.com/uc?id=11JvPCXl6dU7Auci9X1fGAb6MqsPz4Jht&export=download",
  "Entrada Boulevard - Biblioteca": "https://drive.google.com/uc?id=11JeyXsv3_Y_HSCoOMlHPHxMlnoVl80PA&export=download",
  "Entrada Boulevard - Modulo A": "https://drive.google.com/uc?id=11A8_TQ1Vof6LovSMSJWymjumFiRFoeHl&export=download",
  "Modulo O - Modulo G": "https://drive.google.com/uc?id=116cgh9mf9d3ACmi52B97nENGSgHXgbDz&export=download",
  "Modulo W - Modulo V2": "https://drive.google.com/uc?id=10IvUAm650zDVIES5bXEbq_3rpL3ShsFo&export=download"
};
